

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
      - npm install
      - apt-get update
      - apt-get install -y jq
  build:
    commands:
      - ng build 
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - server.js
    - package.json
    - controller/*
