

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16 
  pre_build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo npm install npm@latest -g
      - apt-get update -y
      - apt-get install -y jq
  build:
    commands:
      - npm install -- force
      - npm run build
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - server.js
    - package.json
    - controller/*
